# Generated by Django 4.0.3 on 2022-03-08 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Them',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='title')),
                ('theory', models.TextField(verbose_name='theory')),
            ],
            options={
                'db_table': 'Them',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='number')),
                ('text', models.TextField(verbose_name='text')),
                ('comment', models.TextField(verbose_name='comment')),
                ('them', models.ForeignKey(db_column='Them_id', on_delete=django.db.models.deletion.CASCADE, to='CreateQuestion.them')),
            ],
            options={
                'db_table': 'Question',
            },
        ),
        migrations.CreateModel(
            name='AnswerOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='number')),
                ('text', models.TextField(verbose_name='text')),
                ('right_ans', models.BooleanField(verbose_name='right_ans')),
                ('question', models.ForeignKey(db_column='Question_id', on_delete=django.db.models.deletion.CASCADE, to='CreateQuestion.question')),
            ],
            options={
                'db_table': 'Answer_options',
            },
        ),
    ]
