# Generated by Django 4.0.3 on 2022-03-08 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CreateQuestion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answeroptions',
            name='number',
        ),
        migrations.RemoveField(
            model_name='question',
            name='number',
        ),
    ]
